// lib/utils/mock_defensive_data.dart
//
// Mock data per le azioni difensive (DefensiveActionData) di una partita
// demo (Lazio 2-1 Milan).
//
// PROVVISORIO: usato finche non sara collegata l'API.
//
// // [FAV-extract-mock-actions]
//
// NB: l'import usa la "I" MAIUSCOLA in Interactive_defensive_widget.

import '../widgets/Interactive_defensive_widget.dart';

/// Mock azioni difensive per la squadra di casa.
List<DefensiveActionData> generateMockHomeDefensiveActions() {
  return [
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 2,
        fieldX: 0.16,
        fieldY: 0.37,
        type: 'interception',
        won: true,
        detail: 'Anticipo',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Cataldi',
        minute: 3,
        fieldX: 0.31,
        fieldY: 0.53,
        type: 'tackle',
        won: true,
        detail: 'Scivolata',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 9,
        fieldX: 0.17,
        fieldY: 0.61,
        type: 'clearance',
        won: true,
        detail: 'Di piede',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 12,
        fieldX: 0.2,
        fieldY: 0.52,
        type: 'clearance',
        won: true,
        detail: 'Rinvio',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 13,
        fieldX: 0.18,
        fieldY: 0.22,
        type: 'tackle',
        won: true,
        detail: 'In piedi',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 14,
        fieldX: 0.25,
        fieldY: 0.71,
        type: 'tackle',
        won: true,
        detail: 'Contrasto',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Lazzari',
        minute: 16,
        fieldX: 0.21,
        fieldY: 0.9,
        type: 'tackle',
        won: true,
        detail: 'In piedi',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Guendouzi',
        minute: 18,
        fieldX: 0.49,
        fieldY: 0.52,
        type: 'tackle',
        won: false,
        detail: 'In piedi',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Marusic',
        minute: 19,
        fieldX: 0.18,
        fieldY: 0.25,
        type: 'interception',
        won: true,
        detail: 'Intercetto',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 21,
        fieldX: 0.2,
        fieldY: 0.4,
        type: 'interception',
        won: true,
        detail: 'Anticipo',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 22,
        fieldX: 0.13,
        fieldY: 0.58,
        type: 'tackle',
        won: true,
        detail: 'Tackle laterale',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Guendouzi',
        minute: 23,
        fieldX: 0.41,
        fieldY: 0.77,
        type: 'interception',
        won: true,
        detail: 'Lettura',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Cataldi',
        minute: 27,
        fieldX: 0.46,
        fieldY: 0.5,
        type: 'interception',
        won: true,
        detail: 'Anticipo',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Pedro',
        minute: 29,
        fieldX: 0.53,
        fieldY: 0.2,
        type: 'tackle',
        won: true,
        detail: 'In piedi',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 31,
        fieldX: 0.2,
        fieldY: 0.23,
        type: 'clearance',
        won: true,
        detail: 'Rinvio',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 33,
        fieldX: 0.18,
        fieldY: 0.3,
        type: 'interception',
        won: true,
        detail: 'Anticipo',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 35,
        fieldX: 0.14,
        fieldY: 0.41,
        type: 'clearance',
        won: true,
        detail: 'Di testa',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Cataldi',
        minute: 36,
        fieldX: 0.42,
        fieldY: 0.52,
        type: 'tackle',
        won: true,
        detail: 'Tackle laterale',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 37,
        fieldX: 0.19,
        fieldY: 0.22,
        type: 'tackle',
        won: true,
        detail: 'In piedi',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Guendouzi',
        minute: 41,
        fieldX: 0.4,
        fieldY: 0.49,
        type: 'tackle',
        won: true,
        detail: 'In piedi',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 48,
        fieldX: 0.22,
        fieldY: 0.57,
        type: 'clearance',
        won: true,
        detail: 'Di piede',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 50,
        fieldX: 0.24,
        fieldY: 0.4,
        type: 'clearance',
        won: true,
        detail: 'Di testa',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 53,
        fieldX: 0.22,
        fieldY: 0.68,
        type: 'clearance',
        won: true,
        detail: 'Rinvio',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 55,
        fieldX: 0.2,
        fieldY: 0.62,
        type: 'interception',
        won: true,
        detail: 'Anticipo',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Lazzari',
        minute: 56,
        fieldX: 0.25,
        fieldY: 0.91,
        type: 'tackle',
        won: false,
        detail: 'Scivolata',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 60,
        fieldX: 0.12,
        fieldY: 0.5,
        type: 'clearance',
        won: true,
        detail: 'Di piede',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Lazzari',
        minute: 61,
        fieldX: 0.18,
        fieldY: 0.87,
        type: 'interception',
        won: true,
        detail: 'Intercetto',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Guendouzi',
        minute: 64,
        fieldX: 0.26,
        fieldY: 0.73,
        type: 'tackle',
        won: true,
        detail: 'Scivolata',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Cataldi',
        minute: 66,
        fieldX: 0.28,
        fieldY: 0.46,
        type: 'tackle',
        won: false,
        detail: 'In piedi',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Guendouzi',
        minute: 69,
        fieldX: 0.34,
        fieldY: 0.3,
        type: 'tackle',
        won: true,
        detail: 'Scivolata',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Marusic',
        minute: 70,
        fieldX: 0.15,
        fieldY: 0.1,
        type: 'tackle',
        won: true,
        detail: 'Tackle laterale',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 73,
        fieldX: 0.12,
        fieldY: 0.56,
        type: 'tackle',
        won: false,
        detail: 'In piedi',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 74,
        fieldX: 0.09,
        fieldY: 0.75,
        type: 'clearance',
        won: true,
        detail: 'Rinvio',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Marusic',
        minute: 76,
        fieldX: 0.28,
        fieldY: 0.14,
        type: 'tackle',
        won: true,
        detail: 'Contrasto',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Cataldi',
        minute: 82,
        fieldX: 0.38,
        fieldY: 0.26,
        type: 'interception',
        won: true,
        detail: 'Lettura',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 83,
        fieldX: 0.16,
        fieldY: 0.36,
        type: 'interception',
        won: true,
        detail: 'Intercetto',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Patric',
        minute: 84,
        fieldX: 0.14,
        fieldY: 0.6,
        type: 'tackle',
        won: false,
        detail: 'Scivolata',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Vecino',
        minute: 87,
        fieldX: 0.43,
        fieldY: 0.44,
        type: 'tackle',
        won: true,
        detail: 'Tackle laterale',
        isHomeTeam: true),
    DefensiveActionData(
        playerName: 'Romagnoli',
        minute: 88,
        fieldX: 0.12,
        fieldY: 0.64,
        type: 'tackle',
        won: true,
        detail: 'Scivolata',
        isHomeTeam: true),
  ];
}

/// Mock azioni difensive per la squadra in trasferta.
List<DefensiveActionData> generateMockAwayDefensiveActions() {
  return [
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 3,
        fieldX: 0.19,
        fieldY: 0.52,
        type: 'clearance',
        won: true,
        detail: 'Di testa',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 8,
        fieldX: 0.15,
        fieldY: 0.72,
        type: 'tackle',
        won: true,
        detail: 'Scivolata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Calabria',
        minute: 9,
        fieldX: 0.12,
        fieldY: 0.11,
        type: 'interception',
        won: true,
        detail: 'Intercetto',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 11,
        fieldX: 0.11,
        fieldY: 0.48,
        type: 'clearance',
        won: true,
        detail: 'Spazzata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 14,
        fieldX: 0.22,
        fieldY: 0.71,
        type: 'clearance',
        won: true,
        detail: 'Di testa',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 15,
        fieldX: 0.09,
        fieldY: 0.64,
        type: 'interception',
        won: true,
        detail: 'Anticipo',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Pulisic',
        minute: 16,
        fieldX: 0.47,
        fieldY: 0.22,
        type: 'tackle',
        won: false,
        detail: 'Scivolata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tomori',
        minute: 17,
        fieldX: 0.15,
        fieldY: 0.51,
        type: 'tackle',
        won: true,
        detail: 'In piedi',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tonali',
        minute: 18,
        fieldX: 0.27,
        fieldY: 0.33,
        type: 'tackle',
        won: true,
        detail: 'Tackle laterale',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 19,
        fieldX: 0.11,
        fieldY: 0.52,
        type: 'interception',
        won: true,
        detail: 'Lettura',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 23,
        fieldX: 0.24,
        fieldY: 0.71,
        type: 'clearance',
        won: true,
        detail: 'Spazzata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Theo Hernandez',
        minute: 25,
        fieldX: 0.1,
        fieldY: 0.85,
        type: 'interception',
        won: true,
        detail: 'Anticipo',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Bennacer',
        minute: 32,
        fieldX: 0.4,
        fieldY: 0.61,
        type: 'tackle',
        won: true,
        detail: 'Contrasto',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Bennacer',
        minute: 33,
        fieldX: 0.28,
        fieldY: 0.73,
        type: 'tackle',
        won: true,
        detail: 'Scivolata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Bennacer',
        minute: 35,
        fieldX: 0.48,
        fieldY: 0.32,
        type: 'interception',
        won: true,
        detail: 'Lettura',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Calabria',
        minute: 38,
        fieldX: 0.33,
        fieldY: 0.21,
        type: 'tackle',
        won: true,
        detail: 'Contrasto',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tonali',
        minute: 40,
        fieldX: 0.29,
        fieldY: 0.7,
        type: 'interception',
        won: true,
        detail: 'Intercetto',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Theo Hernandez',
        minute: 42,
        fieldX: 0.28,
        fieldY: 0.76,
        type: 'tackle',
        won: true,
        detail: 'Scivolata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tomori',
        minute: 44,
        fieldX: 0.12,
        fieldY: 0.74,
        type: 'interception',
        won: true,
        detail: 'Anticipo',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 47,
        fieldX: 0.1,
        fieldY: 0.6,
        type: 'tackle',
        won: true,
        detail: 'Contrasto',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tonali',
        minute: 49,
        fieldX: 0.47,
        fieldY: 0.73,
        type: 'tackle',
        won: false,
        detail: 'Tackle laterale',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 51,
        fieldX: 0.11,
        fieldY: 0.2,
        type: 'clearance',
        won: true,
        detail: 'Rinvio',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Kjaer',
        minute: 53,
        fieldX: 0.16,
        fieldY: 0.33,
        type: 'clearance',
        won: true,
        detail: 'Di testa',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tomori',
        minute: 54,
        fieldX: 0.12,
        fieldY: 0.48,
        type: 'clearance',
        won: true,
        detail: 'Di piede',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tonali',
        minute: 60,
        fieldX: 0.28,
        fieldY: 0.59,
        type: 'tackle',
        won: true,
        detail: 'Tackle laterale',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tomori',
        minute: 64,
        fieldX: 0.17,
        fieldY: 0.37,
        type: 'clearance',
        won: true,
        detail: 'Di piede',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Theo Hernandez',
        minute: 69,
        fieldX: 0.09,
        fieldY: 0.85,
        type: 'tackle',
        won: true,
        detail: 'In piedi',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Calabria',
        minute: 73,
        fieldX: 0.27,
        fieldY: 0.2,
        type: 'tackle',
        won: false,
        detail: 'Contrasto',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tomori',
        minute: 75,
        fieldX: 0.17,
        fieldY: 0.63,
        type: 'clearance',
        won: true,
        detail: 'Spazzata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Bennacer',
        minute: 76,
        fieldX: 0.4,
        fieldY: 0.45,
        type: 'tackle',
        won: false,
        detail: 'Tackle laterale',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tomori',
        minute: 77,
        fieldX: 0.12,
        fieldY: 0.4,
        type: 'tackle',
        won: false,
        detail: 'In piedi',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tonali',
        minute: 81,
        fieldX: 0.48,
        fieldY: 0.76,
        type: 'tackle',
        won: true,
        detail: 'Scivolata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tomori',
        minute: 82,
        fieldX: 0.18,
        fieldY: 0.2,
        type: 'tackle',
        won: false,
        detail: 'Scivolata',
        isHomeTeam: false),
    DefensiveActionData(
        playerName: 'Tonali',
        minute: 87,
        fieldX: 0.5,
        fieldY: 0.68,
        type: 'interception',
        won: true,
        detail: 'Intercetto',
        isHomeTeam: false),
  ];
}
