// lib/utils/mock_match_events.dart
//
// Mock data per gli eventi (LocalMatchEvent) di una partita demo
// (Lazio 2-1 Milan): goal, corner, falli, ammonizioni, cambi, etc.
//
// PROVVISORIO: usato finche non sara collegata l'API che fornira
// eventi reali per match_id.
//
// Quando arrivera l'API:
//   - Rimuovere questo file
//   - Sostituire il wrapper nel monolite con chiamata API
//
// // [FAV-extract-mock-events]

import 'package:flutter/material.dart';
import '../generated/l10n.dart';
import '../models/local_match_event.dart';

List<LocalMatchEvent> generateMockMatchEvents(BuildContext context) {
  return [
    // === 1° TEMPO ===
    const LocalMatchEvent(
        type: 'corner',
        minute: 5,
        playerName: 'Zaccagni',
        detail: 'CORNER_LEFT',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 7,
        playerName: 'Tonali',
        detail: 'FOUL_ON:Zaccagni',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 8,
        playerName: 'Pedro',
        detail: 'Tiro parato',
        subDetail: 'Destro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 10,
        playerName: 'Tomori',
        detail: 'FOUL_ON:Zaccagni',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 11,
        playerName: 'Romagnoli',
        detail: 'FOUL_ON:Giroud',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'goal',
        minute: 12,
        playerName: 'Immobile',
        detail: 'Assist: Zaccagni',
        subDetail: 'Destro da area',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 15,
        playerName: 'Cataldi',
        detail: 'FOUL_ON:Leao',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 18,
        playerName: 'Leao',
        detail: 'Tiro parato',
        subDetail: 'Sinistro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 19,
        playerName: 'Theo Hernandez',
        detail: 'CORNER_LEFT',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 20,
        playerName: 'Guendouzi',
        detail: 'FOUL_ON:Bennacer',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 15,
        playerName: 'Zaccagni',
        detail: 'Tiro fuori',
        subDetail: 'Sinistro',
        isHomeTeam: true,
        playerPhoto: null),
    // ✅ FIX: era Pellegrini (non in formazione) → Patric
    LocalMatchEvent(
        type: 'yellowCard',
        minute: 23,
        playerName: 'Patric',
        detail: S.of(context)!.falloTattico,
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 25,
        playerName: 'Zaccagni',
        detail: 'CORNER_RIGHT',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 26,
        playerName: 'Calabria',
        detail: 'FOUL_ON:Zaccagni',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 41,
        playerName: 'Pedro',
        detail: 'Tiro fuori',
        subDetail: 'Destro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 29,
        playerName: 'Lazzari',
        detail: 'FOUL_ON:Leao',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 35,
        playerName: 'Leao',
        detail: 'Tiro fuori',
        subDetail: 'Sinistro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 31,
        playerName: 'Bennacer',
        detail: 'FOUL_ON:Luis Alberto',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 32,
        playerName: 'Luis Alberto',
        detail: 'CORNER_LEFT',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 33,
        playerName: 'Zaccagni',
        detail: 'Tiro parato',
        subDetail: 'Sinistro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'yellowCard',
        minute: 34,
        playerName: 'Theo Hernandez',
        detail: 'FOUL_ON:Immobile',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 36,
        playerName: 'Marusic',
        detail: 'FOUL_ON:Pulisic',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 37,
        playerName: 'Zaccagni',
        detail: 'CORNER_RIGHT',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 37,
        playerName: 'Bennacer',
        detail: 'FOUL_ON:Pedro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 38,
        playerName: 'Luis Alberto',
        detail: 'Tiro fuori',
        subDetail: 'Destro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 39,
        playerName: 'Tomori',
        detail: 'FOUL_ON:Pedro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 40,
        playerName: 'Theo Hernandez',
        detail: 'CORNER_RIGHT',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'offside',
        minute: 41,
        playerName: 'Giroud',
        detail: 'OFFSIDE_ACTIVE',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'offside',
        minute: 28,
        playerName: 'Immobile',
        detail: 'OFFSIDE_PASSIVE',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'offside',
        minute: 58,
        playerName: 'Leao',
        detail: 'OFFSIDE_ACTIVE',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'offside',
        minute: 70,
        playerName: 'Felipe Anderson',
        detail: 'OFFSIDE_ACTIVE',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'offside',
        minute: 82,
        playerName: 'Immobile',
        detail: 'OFFSIDE_PASSIVE',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 42,
        playerName: 'Theo Hernandez',
        detail: 'Tiro fuori',
        subDetail: 'Sinistro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 44,
        playerName: 'Romagnoli',
        detail: 'FOUL_ON:Giroud',
        isHomeTeam: true,
        playerPhoto: null),
    // === 2° TEMPO ===
    const LocalMatchEvent(
        type: 'shot',
        minute: 48,
        playerName: 'Pedro',
        detail: 'Tiro bloccato',
        subDetail: 'Destro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 49,
        playerName: 'Kjaer',
        detail: 'FOUL_ON:Immobile',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 50,
        playerName: 'Bennacer',
        detail: 'Tiro bloccato',
        subDetail: 'Destro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'substitution',
        minute: 52,
        playerName: 'Pedro',
        detail: 'Felipe Anderson',
        subDetail: 'Cambio',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 52,
        playerName: 'Luis Alberto',
        detail: 'Tiro parato',
        subDetail: 'Destro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 53,
        playerName: 'Zaccagni',
        detail: 'CORNER_RIGHT',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 54,
        playerName: 'Patric',
        detail: 'FOUL_ON:Brahim Diaz',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 55,
        playerName: 'Felipe Anderson',
        detail: 'Tiro fuori',
        subDetail: 'Sinistro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'goal',
        minute: 56,
        playerName: 'Giroud',
        detail: 'Assist: Leao',
        subDetail: 'Colpo di testa',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 57,
        playerName: 'Lazzari',
        detail: 'FOUL_ON:Theo',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 58,
        playerName: 'Calabria',
        detail: 'FOUL_ON:Felipe Anderson',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 59,
        playerName: 'Zaccagni',
        detail: 'CORNER_LEFT',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 60,
        playerName: 'Cataldi',
        detail: 'Tiro parato',
        subDetail: 'Destro',
        isHomeTeam: true,
        playerPhoto: null),
    LocalMatchEvent(
        type: 'yellowCard',
        minute: 61,
        playerName: 'Bennacer',
        detail: S.of(context)!.falloTattico,
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 63,
        playerName: 'Pulisic',
        detail: 'Tiro fuori',
        subDetail: 'Destro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 64,
        playerName: 'Calabria',
        detail: 'FOUL_ON:Marusic',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'substitution',
        minute: 65,
        playerName: 'Luis Alberto',
        detail: 'Marcos Antonio',
        subDetail: 'Cambio',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 66,
        playerName: 'Tonali',
        detail: 'FOUL_ON:Cataldi',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 67,
        playerName: 'Immobile',
        detail: 'Tiro bloccato',
        subDetail: 'Colpo di testa',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'substitution',
        minute: 68,
        playerName: 'Cataldi',
        detail: 'Vecino',
        subDetail: 'Cambio',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 69,
        playerName: 'Vecino',
        detail: 'FOUL_ON:Brahim Diaz',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 71,
        playerName: 'Immobile',
        detail: 'Tiro parato',
        subDetail: 'Colpo di testa',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 71,
        playerName: 'Theo Hernandez',
        detail: 'CORNER_RIGHT',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 72,
        playerName: 'Brahim Diaz',
        detail: 'FOUL_ON:Guendouzi',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'substitution',
        minute: 72,
        playerName: 'Tonali',
        detail: 'Adli',
        subDetail: 'Cambio',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 73,
        playerName: 'Guendouzi',
        detail: 'Tiro bloccato',
        subDetail: 'Destro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 74,
        playerName: 'Guendouzi',
        detail: 'FOUL_ON:Tonali',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'substitution',
        minute: 75,
        playerName: 'Giroud',
        detail: 'Jovic',
        subDetail: 'Cambio',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 71,
        playerName: 'Pulisic',
        detail: 'Tiro bloccato',
        subDetail: 'Destro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'corner',
        minute: 76,
        playerName: 'Theo Hernandez',
        detail: 'CORNER_LEFT',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'goal',
        minute: 78,
        playerName: 'Felipe Anderson',
        detail: 'Assist: Immobile',
        subDetail: 'Sinistro da area',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 79,
        playerName: 'Kjaer',
        detail: 'FOUL_ON:Immobile',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 80,
        playerName: 'Brahim Diaz',
        detail: 'Tiro parato',
        subDetail: 'Destro',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 81,
        playerName: 'Tomori',
        detail: 'FOUL_ON:Immobile',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 83,
        playerName: 'Marusic',
        detail: 'FOUL_ON:Leao',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'substitution',
        minute: 83,
        playerName: 'Brahim Diaz',
        detail: 'Saelemaekers',
        subDetail: 'Cambio',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'shot',
        minute: 85,
        playerName: 'Guendouzi',
        detail: 'Tiro fuori',
        subDetail: 'Destro',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'yellowCard',
        minute: 85,
        playerName: 'Tomori',
        detail: 'FOUL_ON:Felipe Anderson',
        isHomeTeam: false,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 86,
        playerName: 'Pulisic',
        detail: 'FOUL_ON:Marusic',
        isHomeTeam: false,
        playerPhoto: null),
    LocalMatchEvent(
        type: 'yellowCard',
        minute: 88,
        playerName: 'Guendouzi',
        detail: S.of(context)!.proteste,
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 89,
        playerName: 'Patric',
        detail: 'FOUL_ON:Leao',
        isHomeTeam: true,
        playerPhoto: null),
    const LocalMatchEvent(
        type: 'foul',
        minute: 90,
        playerName: 'Leao',
        detail: 'FOUL_ON:Lazzari',
        isHomeTeam: false,
        playerPhoto: null),
  ];
}
