// lib/utils/mock_shot_data.dart
//
// Mock data per i tiri (ShotData) di una partita demo (Lazio 2-1 Milan).
//
// PROVVISORIO: usato finche non sara collegata l'API che fornira
// shot data reali per match_id.
//
// Quando arrivera l'API:
//   - Rimuovere questo file
//   - Sostituire le chiamate in _loadShotData con chiamata API
//
// // [FAV-extract-mock-actions]

import '../widgets/interactive_shot_map_widget.dart';

/// Mock shot data per la squadra di casa.
List<ShotData> generateMockHomeShots() {
  return [
    // --- GOAL (2) --- contano come "in porta"
    ShotData(
        playerName: 'Immobile',
        playerPhoto: '',
        minute: 12,
        startX: 0.55,
        startY: 0.22,
        goalX: 0.72,
        goalY: 0.65,
        type: 'goal',
        xG: 0.45,
        xGOT: 0.52,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'In basso a destra'),
    ShotData(
        playerName: 'Felipe Anderson',
        playerPhoto: '',
        minute: 78,
        startX: 0.38,
        startY: 0.28,
        goalX: 0.25,
        goalY: 0.70,
        type: 'goal',
        xG: 0.38,
        xGOT: 0.55,
        situation: 'Contropiede',
        shotType: 'Tiro di sinistro',
        goalZone: 'In basso a sinistra'),

    // --- ON TARGET (5) --- parate del portiere
    ShotData(
        playerName: 'Pedro',
        playerPhoto: '',
        minute: 8,
        startX: 0.68,
        startY: 0.32,
        goalX: 0.80,
        goalY: 0.45,
        type: 'on_target',
        xG: 0.15,
        xGOT: 0.18,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Centro destra'),
    ShotData(
        playerName: 'Zaccagni',
        playerPhoto: '',
        minute: 33,
        startX: 0.30,
        startY: 0.35,
        goalX: 0.40,
        goalY: 0.50,
        type: 'on_target',
        xG: 0.18,
        xGOT: 0.22,
        situation: 'Gioco aperto',
        shotType: 'Tiro di sinistro',
        goalZone: 'Centro'),
    ShotData(
        playerName: 'Luis Alberto',
        playerPhoto: '',
        minute: 52,
        startX: 0.45,
        startY: 0.50,
        goalX: 0.55,
        goalY: 0.30,
        type: 'on_target',
        xG: 0.12,
        xGOT: 0.15,
        situation: 'Calcio di punizione',
        shotType: 'Tiro di destro',
        goalZone: 'In alto a destra'),
    ShotData(
        playerName: 'Cataldi',
        playerPhoto: '',
        minute: 60,
        startX: 0.50,
        startY: 0.60,
        goalX: 0.45,
        goalY: 0.55,
        type: 'on_target',
        xG: 0.08,
        xGOT: 0.10,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Centro'),
    ShotData(
        playerName: 'Immobile',
        playerPhoto: '',
        minute: 71,
        startX: 0.52,
        startY: 0.18,
        goalX: 0.60,
        goalY: 0.40,
        type: 'on_target',
        xG: 0.32,
        xGOT: 0.28,
        situation: 'Gioco aperto',
        shotType: 'Colpo di testa',
        goalZone: 'Centro destra'),

    // --- OFF TARGET (5) --- fuori dallo specchio della porta
    ShotData(
        playerName: 'Zaccagni',
        playerPhoto: '',
        minute: 15,
        startX: 0.25,
        startY: 0.40,
        goalX: -0.20,
        goalY: 0.40,
        type: 'off_target',
        xG: 0.06,
        situation: 'Gioco aperto',
        shotType: 'Tiro di sinistro',
        goalZone: 'Largo a sinistra'),
    ShotData(
        playerName: 'Luis Alberto',
        playerPhoto: '',
        minute: 38,
        startX: 0.48,
        startY: 0.55,
        goalX: 0.50,
        goalY: -0.25,
        type: 'off_target',
        xG: 0.05,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Sopra la traversa'),
    ShotData(
        playerName: 'Pedro',
        playerPhoto: '',
        minute: 41,
        startX: 0.75,
        startY: 0.38,
        goalX: 1.25,
        goalY: 0.35,
        type: 'off_target',
        xG: 0.08,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Largo a destra'),
    ShotData(
        playerName: 'Felipe Anderson',
        playerPhoto: '',
        minute: 55,
        startX: 0.42,
        startY: 0.42,
        goalX: 0.45,
        goalY: -0.30,
        type: 'off_target',
        xG: 0.10,
        situation: 'Gioco aperto',
        shotType: 'Tiro di sinistro',
        goalZone: 'Sopra la traversa'),
    ShotData(
        playerName: 'Guendouzi',
        playerPhoto: '',
        minute: 85,
        startX: 0.62,
        startY: 0.65,
        goalX: 1.15,
        goalY: 0.25,
        type: 'off_target',
        xG: 0.04,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Largo a destra'),

    // --- BLOCKED (3) --- respinti dai difensori
    ShotData(
        playerName: 'Pedro',
        playerPhoto: '',
        minute: 48,
        startX: 0.60,
        startY: 0.35,
        goalX: 0.55,
        goalY: 0.50,
        type: 'blocked',
        xG: 0.14,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Centro'),
    ShotData(
        playerName: 'Immobile',
        playerPhoto: '',
        minute: 67,
        startX: 0.50,
        startY: 0.20,
        goalX: 0.50,
        goalY: 0.45,
        type: 'blocked',
        xG: 0.22,
        situation: 'Gioco aperto',
        shotType: 'Colpo di testa',
        goalZone: 'Centro'),
    ShotData(
        playerName: 'Guendouzi',
        playerPhoto: '',
        minute: 73,
        startX: 0.55,
        startY: 0.58,
        goalX: 0.48,
        goalY: 0.55,
        type: 'blocked',
        xG: 0.06,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Centro'),
  ];
}

/// Mock shot data per la squadra in trasferta.
List<ShotData> generateMockAwayShots() {
  return [
    ShotData(
        playerName: 'Giroud',
        playerPhoto: '',
        minute: 56,
        startX: 0.50,
        startY: 0.20,
        goalX: 0.60,
        goalY: 0.25,
        type: 'goal',
        xG: 0.38,
        xGOT: 0.44,
        situation: 'Gioco aperto',
        shotType: 'Colpo di testa',
        goalZone: 'In alto a destra'),
    ShotData(
        playerName: 'Leao',
        playerPhoto: '',
        minute: 18,
        startX: 0.25,
        startY: 0.35,
        goalX: 0.30,
        goalY: 0.50,
        type: 'on_target',
        xG: 0.28,
        xGOT: 0.25,
        situation: 'Gioco aperto',
        shotType: 'Tiro di sinistro',
        goalZone: 'Centro sinistra'),
    ShotData(
        playerName: 'Brahim Diaz',
        playerPhoto: '',
        minute: 80,
        startX: 0.45,
        startY: 0.45,
        goalX: 0.40,
        goalY: 0.30,
        type: 'on_target',
        xG: 0.10,
        xGOT: 0.12,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'In alto a sinistra'),
    ShotData(
        playerName: 'Leao',
        playerPhoto: '',
        minute: 35,
        startX: 0.20,
        startY: 0.30,
        goalX: -0.18,
        goalY: 0.50,
        type: 'off_target',
        xG: 0.12,
        situation: 'Gioco aperto',
        shotType: 'Tiro di sinistro',
        goalZone: 'Largo a sinistra'),
    ShotData(
        playerName: 'Theo Hernandez',
        playerPhoto: '',
        minute: 42,
        startX: 0.18,
        startY: 0.55,
        goalX: 0.40,
        goalY: -0.30,
        type: 'off_target',
        xG: 0.05,
        situation: 'Gioco aperto',
        shotType: 'Tiro di sinistro',
        goalZone: 'Sopra la traversa'),
    ShotData(
        playerName: 'Pulisic',
        playerPhoto: '',
        minute: 63,
        startX: 0.70,
        startY: 0.40,
        goalX: 1.20,
        goalY: 0.30,
        type: 'off_target',
        xG: 0.09,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Largo a destra'),
    ShotData(
        playerName: 'Bennacer',
        playerPhoto: '',
        minute: 50,
        startX: 0.55,
        startY: 0.60,
        goalX: 0.50,
        goalY: 0.50,
        type: 'blocked',
        xG: 0.07,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Centro'),
    ShotData(
        playerName: 'Pulisic',
        playerPhoto: '',
        minute: 71,
        startX: 0.65,
        startY: 0.38,
        goalX: 0.55,
        goalY: 0.45,
        type: 'blocked',
        xG: 0.15,
        situation: 'Gioco aperto',
        shotType: 'Tiro di destro',
        goalZone: 'Centro'),
  ];
}
